primeiro_projeto/enquete/urls.py
from django.urls import path
from . import views

app_name = "enquete"

urlpatterns = [
    path('', views.index, name='index'),
    path('resultado/', views.resultado, name='resultado'),
]

primeiro_projeto/imc/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('calcular/', views.calcular_imc, name='calc')
]

primeiro_projeto/primeiro_projeto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("imc/", include('imc.urls')),
    path("enquete/", include('enquete.urls')),
]

primeiro_projeto/enquete/models.py
from django.db import models

# Create your models here.

primeiro_projeto/imc/models.py
from django.db import models

# Create your models here.

primeiro_projeto/enquete/views.py
from django.shortcuts import render
from . import services

# Create your views here.

def index(request):
    return render(request, 'enquetes/index.html')

def resultado(request):
    resultado = int(request.POST.get("radio")) # o atributo name do HTML é o que é recebido no request.GET.get
    services.votar(resultado)
    contexto = services.resultado()
    return render(request, 'enquetes/resultado.html', contexto)

primeiro_projeto/imc/views.py
from django.shortcuts import render
from . import services

# Create your views here.

def index(request):
    return render(request, 'index.html') # renderizar a requisição com a página HTML

def calcular_imc(request):
    altura = float(request.POST.get('altura')) # pega a altura pela requisição do formulário(action) pelo nome atribuido no template
    peso = float(request.POST.get('peso')) # pega a altura pela requisição do formulário(action) pelo nome atribuido no template
    contexto = services.calcular_imc(altura, peso)
    return render(request, 'imc.html', contexto) # os nomes dos valores do dict serão utilizados no tmeplate imc.html

primeiro_projeto/enquete/templates/enquetes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Enquete App</title>
    <style>
        h1 {
            text-align: center;
        }
        form {
            margin-top: 5em;
            margin-left: 1em;
        }
        input, label {
            margin-bottom: 2em;
        }
    </style>
</head>
<body>
    <header>
        <h1>Qual maior ídolo da história do Vasco?</h1>
    </header>
    <main>
        <form action = "{% url 'enquete:resultado' %}" method="POST"> <!-- trocar a URL do action pelo name associada a view no urls.py, ex: action = "{{ resultado }}" -->
            <!-- esse enquete: é por causa do app_name no urls.py, para que eu possa ter names nos paths iguais entre apps sem conflitar -->
            {% csrf_token %} <!-- proteger contra phishing mandando de um dominio para o mesmo e bloqueando caso não seja -->
            <input type = "radio" id = "Dinamite" name = "radio" value = "0">
            <label for = "Dinamite">Roberto Dinamite</label>
            <br>
            <input type = "radio" id = "Romario" name = "radio" value = "1">
            <label for = "Romario">Romário</label>
            <br>
            <input type = "radio" id = "Edmundo" name = "radio" value = "2">
            <label for = "Edmundo">Edmundo</label>
            <br>
            <input type = "radio" id = "Barbosa" name = "radio" value = "3">
            <label for = "Barbosa">Barbosa</label>
            <br>
            <button type = "submit" value = "Enviar">Enviar</button>
        </form>
    </main>
</body>
</html>

primeiro_projeto/enquete/templates/enquetes/resultado.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Resultado da Enquete</title>
        <style>
            h1 {
                text-align: center;
            }
            ol {
                list-style-type: none;
                margin-top: 5em;
                margin-left: 1em;
            }
            li {
                margin-bottom: 2em;
            }

        </style>
    </head>
    <body>
        <header>
            <h1>Resultado da Enquete</h1>
        </header>
        <main>
            <ol>
                {% for alternativa in resultado %}
                <li>{{ alternativa.nome }}: {{ alternativa.votos }}</li>
                {% endfor %}
            </ol>
        </main>
    </body>
</html>

primeiro_projeto/imc/templates/imc.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Resultado IMC</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
</head>
<body>
    <section class="section">
        <div class="container">
            <h1 class="title has-text-centered">Resultado do Cálculo do IMC</h1>
            <div class="box">
                <p><strong>Peso:</strong> {{ peso }} kg</p> <!-- valor do peso -->
                <p><strong>Altura:</strong> {{ altura }} m</p> <!-- valor da altura -->
                <p><strong>IMC:</strong> {{ imc }}</p> <!-- valor do imc -->
                <p><strong>Classificação:</strong> {{ classificacao }}</p> <!-- valor da classificação -->
            </div>
            <div class="has-text-centered">
                <a href="/imc" class="button is-primary">Calcular Novamente</a> 
                <!-- para retornar para a pagina inicial tem q começar com o / -->
            </div>
        </div>
    </section>
    {% load static %}
    <script src = "{% static 'imc/javascript/app.js' %}"></script>
    <script>
        exibirClassificacao("{{ classificacao }}");
    </script>
</body>
</html>

primeiro_projeto/imc/templates/index.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Calculadora de IMC</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.4/css/bulma.min.css">
</head>
<body>
    <header>
        <h1 class="title">Calculadora de IMC</h1>
    </header>
    <main>
        <section class="section">
            <div class="container">
                <form id="imc-form"  action="calcular/" method="POST">
                    {% csrf_token %}
                    <label class="label">Altura (m):</label>
                    <div class="control">
                        <input type="number" id="altura" name="altura" step="0.01" class="input" required>
                    </div>
                    <label class="label">Peso (kg):</label>
                    <div class="control">
                        <input type="number" id="peso" name="peso" step="0.1" class="input" required>
                    </div>
                    <button type="submit" class="button is-link">Calcular IMC</button>
                </form>
            </div>
        </section>
    </main>
    <footer class="footer">
        <div class="content has-text-centered">
            <p>&copy; 2025 Calculadora de IMC</p>
        </div>
    </footer>
</body>
</html>